apiVersion: batch/v1
kind: CronJob
metadata:
  name: dot-project-sync
  namespace: maintainerd
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 600
  jobTemplate:
    metadata: {}
    spec:
      ttlSecondsAfterFinished: 3600
      backoffLimit: 1
      template:
        metadata: {}
        spec:
          containers:
          - image: ghcr.io/robertkielty/maintainerd-dot-project-sync:latest
            imagePullPolicy: Always
            name: dot-project-sync
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            env:
            - name: DOT_PROJECT_SYNC_TIMEOUT
              value: "50m"
            envFrom:
            - secretRef:
                name: maintainerd-db-env
            - secretRef:
                name: maintainerd-server-env
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: ghcr-secret
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
