apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerd-db
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # no storageClassName -> use cluster default
