apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maintainerd-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # no storageClassName -> use cluster default

