apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: maintainerd

resources:
  - ../../base

patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-deployment.yaml

images:
  - name: ghcr.io/robertkielty/maintainerd
    newTag: v0.1.0 # set to a released tag
